package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name="administrador"
    ,catalog="sge"
)
public class Administrador  implements java.io.Serializable {


     private int codAdministrador;
     private String nome;
     private String dataNascimento;
     private String email;
     private String senha;
     

    public Administrador() {
    }

	
    public Administrador(int codAdministrador, String nome) {
        this.codAdministrador = codAdministrador;
        this.nome = nome;
    }
    public Administrador(int codAdministrador, String nome, String dataNascimento, String email, String senha) {
       this.codAdministrador = codAdministrador;
       this.nome = nome;
       this.dataNascimento = dataNascimento;
       this.email = email;
       this.senha = senha;
    }
   
     @Id 

    
    @Column(name="codAdministrador", unique=true, nullable=false)
    public int getCodAdministrador() {
        return this.codAdministrador;
    }
    
    public void setCodAdministrador(int codAdministrador) {
        this.codAdministrador = codAdministrador;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="dataNascimento", length=45)
    public String getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="senha", length=8)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }


}


