package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Certificado generated by hbm2java
 */
@Entity
@Table(name="certificado"
    ,catalog="sge"
)
public class Certificado  implements java.io.Serializable {


     private String codAutencidade;
     private Inscricao inscricao;
     private String descricao;

    public Certificado() {
    }

	
    public Certificado(String codAutencidade, Inscricao inscricao) {
        this.codAutencidade = codAutencidade;
        this.inscricao = inscricao;
    }
    public Certificado(String codAutencidade, Inscricao inscricao, String descricao) {
       this.codAutencidade = codAutencidade;
       this.inscricao = inscricao;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="codAutencidade", unique=true, nullable=false, length=30)
    public String getCodAutencidade() {
        return this.codAutencidade;
    }
    
    public void setCodAutencidade(String codAutencidade) {
        this.codAutencidade = codAutencidade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Inscricao_codInscricao", nullable=false)
    public Inscricao getInscricao() {
        return this.inscricao;
    }
    
    public void setInscricao(Inscricao inscricao) {
        this.inscricao = inscricao;
    }

    
    @Column(name="descricao", length=60)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


