package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name="evento"
    ,catalog="sge"
)
public class Evento  implements java.io.Serializable {


     private int idEvento;
     private Administrador administrador;
     private String nomeEvento;
     private String duracao;
     private String tema;
     private String dataInicioEvento;
     private String dataFimEvento;
     private String dataInicioInscricao;
     private String dataFimInscricao;
     private Set noticias = new HashSet(0);
     private Set galerias = new HashSet(0);
     private Set propostas = new HashSet(0);

    public Evento() {
    }

	
    public Evento(int idEvento, Administrador administrador) {
        this.idEvento = idEvento;
        this.administrador = administrador;
    }
    public Evento(int idEvento, Administrador administrador, String nomeEvento, String duracao, String tema, String dataInicioEvento, String dataFimEvento, String dataInicioInscricao, String dataFimInscricao, Set noticias, Set galerias, Set propostas) {
       this.idEvento = idEvento;
       this.administrador = administrador;
       this.nomeEvento = nomeEvento;
       this.duracao = duracao;
       this.tema = tema;
       this.dataInicioEvento = dataInicioEvento;
       this.dataFimEvento = dataFimEvento;
       this.dataInicioInscricao = dataInicioInscricao;
       this.dataFimInscricao = dataFimInscricao;
       this.noticias = noticias;
       this.galerias = galerias;
       this.propostas = propostas;
    }
   
     @Id 

    
    @Column(name="idEvento", unique=true, nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Administrador_codAdministrador", nullable=false)
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }

    
    @Column(name="nomeEvento", length=45)
    public String getNomeEvento() {
        return this.nomeEvento;
    }
    
    public void setNomeEvento(String nomeEvento) {
        this.nomeEvento = nomeEvento;
    }

    
    @Column(name="duracao", length=10)
    public String getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(String duracao) {
        this.duracao = duracao;
    }

    
    @Column(name="tema", length=50)
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }

    
    @Column(name="dataInicioEvento", length=45)
    public String getDataInicioEvento() {
        return this.dataInicioEvento;
    }
    
    public void setDataInicioEvento(String dataInicioEvento) {
        this.dataInicioEvento = dataInicioEvento;
    }

    
    @Column(name="dataFimEvento", length=45)
    public String getDataFimEvento() {
        return this.dataFimEvento;
    }
    
    public void setDataFimEvento(String dataFimEvento) {
        this.dataFimEvento = dataFimEvento;
    }

    
    @Column(name="dataInicioInscricao", length=45)
    public String getDataInicioInscricao() {
        return this.dataInicioInscricao;
    }
    
    public void setDataInicioInscricao(String dataInicioInscricao) {
        this.dataInicioInscricao = dataInicioInscricao;
    }

    
    @Column(name="dataFimInscricao", length=45)
    public String getDataFimInscricao() {
        return this.dataFimInscricao;
    }
    
    public void setDataFimInscricao(String dataFimInscricao) {
        this.dataFimInscricao = dataFimInscricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set getGalerias() {
        return this.galerias;
    }
    
    public void setGalerias(Set galerias) {
        this.galerias = galerias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evento")
    public Set getPropostas() {
        return this.propostas;
    }
    
    public void setPropostas(Set propostas) {
        this.propostas = propostas;
    }




}


