package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Externo generated by hbm2java
 */
@Entity
@Table(name="externo"
    ,catalog="sge"
)
public class Externo  implements java.io.Serializable {


     private int idExterno;
     private String conhecimento;
     private String nome;
     private String email;
     private String dataNascimento;
     private String senha;
     private Set inscricaos = new HashSet(0);

    public Externo() {
    }

	
    public Externo(int idExterno, String email) {
        this.idExterno = idExterno;
        this.email = email;
    }
    public Externo(int idExterno, String conhecimento, String nome, String email, String dataNascimento, String senha, Set inscricaos) {
       this.idExterno = idExterno;
       this.conhecimento = conhecimento;
       this.nome = nome;
       this.email = email;
       this.dataNascimento = dataNascimento;
       this.senha = senha;
       this.inscricaos = inscricaos;
    }
   
     @Id 

    
    @Column(name="idExterno", unique=true, nullable=false)
    public int getIdExterno() {
        return this.idExterno;
    }
    
    public void setIdExterno(int idExterno) {
        this.idExterno = idExterno;
    }

    
    @Column(name="conhecimento", length=30)
    public String getConhecimento() {
        return this.conhecimento;
    }
    
    public void setConhecimento(String conhecimento) {
        this.conhecimento = conhecimento;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="dataNascimento", length=45)
    public String getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="senha", length=8)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="externo")
    public Set getInscricaos() {
        return this.inscricaos;
    }
    
    public void setInscricaos(Set inscricaos) {
        this.inscricaos = inscricaos;
    }




}


