package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fotos generated by hbm2java
 */
@Entity
@Table(name="fotos"
    ,catalog="sge"
)
public class Fotos  implements java.io.Serializable {


     private int idFoto;
     private Album album;
     private byte[] arquivo;

    public Fotos() {
    }

    public Fotos(int idFoto, Album album, byte[] arquivo) {
       this.idFoto = idFoto;
       this.album = album;
       this.arquivo = arquivo;
    }
   
     @Id 

    
    @Column(name="idFoto", unique=true, nullable=false)
    public int getIdFoto() {
        return this.idFoto;
    }
    
    public void setIdFoto(int idFoto) {
        this.idFoto = idFoto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Album_id", nullable=false)
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }

    
    @Column(name="arquivo", nullable=false)
    public byte[] getArquivo() {
        return this.arquivo;
    }
    
    public void setArquivo(byte[] arquivo) {
        this.arquivo = arquivo;
    }




}


