package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Galeria generated by hbm2java
 */
@Entity
@Table(name="galeria"
    ,catalog="sge"
)
public class Galeria  implements java.io.Serializable {


     private int idGaleria;
     private Evento evento;
     private String data;
     private Set albums = new HashSet(0);

    public Galeria() {
    }

	
    public Galeria(int idGaleria, Evento evento) {
        this.idGaleria = idGaleria;
        this.evento = evento;
    }
    public Galeria(int idGaleria, Evento evento, String data, Set albums) {
       this.idGaleria = idGaleria;
       this.evento = evento;
       this.data = data;
       this.albums = albums;
    }
   
     @Id 

    
    @Column(name="idGaleria", unique=true, nullable=false)
    public int getIdGaleria() {
        return this.idGaleria;
    }
    
    public void setIdGaleria(int idGaleria) {
        this.idGaleria = idGaleria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Evento_id", nullable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

    
    @Column(name="data", length=45)
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="galeria")
    public Set getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set albums) {
        this.albums = albums;
    }




}


