package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gerente generated by hbm2java
 */
@Entity
@Table(name="gerente"
    ,catalog="sge"
)
public class Gerente  implements java.io.Serializable {


     private int codGerente;
     private String nome;
     private String email;
     private String dataNascimento;
     private String senha;

    public Gerente() {
    }

	
    public Gerente(int codGerente, String nome) {
        this.codGerente = codGerente;
        this.nome = nome;
    }
    public Gerente(int codGerente, String nome, String email, String dataNascimento, String senha) {
       this.codGerente = codGerente;
       this.nome = nome;
       this.email = email;
       this.dataNascimento = dataNascimento;
       this.senha = senha;
    }
   
     @Id 

    
    @Column(name="codGerente", unique=true, nullable=false)
    public int getCodGerente() {
        return this.codGerente;
    }
    
    public void setCodGerente(int codGerente) {
        this.codGerente = codGerente;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="dataNascimento", length=45)
    public String getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="senha", length=8)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

}


