package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Inscricao generated by hbm2java
 */
@Entity
@Table(name="inscricao"
    ,catalog="sge"
)
public class Inscricao  implements java.io.Serializable {


     private int codInscricao;
     private Aluno aluno;
     private Externo externo;
     private Proposta proposta;
     private String tipo;
     private Boolean frequencia;


    public Inscricao() {
    }

	
    public Inscricao(int codInscricao, Aluno aluno, Externo externo, Proposta proposta) {
        this.codInscricao = codInscricao;
        this.aluno = aluno;
        this.externo = externo;
        this.proposta = proposta;
    }
    public Inscricao(int codInscricao, Aluno aluno, Externo externo, Proposta proposta, String tipo, Boolean frequencia) {
       this.codInscricao = codInscricao;
       this.aluno = aluno;
       this.externo = externo;
       this.proposta = proposta;
       this.tipo = tipo;
       this.frequencia = frequencia;

    }
   
     @Id 

    
    @Column(name="codInscricao", unique=true, nullable=false)
    public int getCodInscricao() {
        return this.codInscricao;
    }
    
    public void setCodInscricao(int codInscricao) {
        this.codInscricao = codInscricao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Aluno_matricula", nullable=false)
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Externo_id", nullable=false)
    public Externo getExterno() {
        return this.externo;
    }
    
    public void setExterno(Externo externo) {
        this.externo = externo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proposta_id", nullable=false)
    public Proposta getProposta() {
        return this.proposta;
    }
    
    public void setProposta(Proposta proposta) {
        this.proposta = proposta;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="frequencia")
    public Boolean getFrequencia() {
        return this.frequencia;
    }
    
    public void setFrequencia(Boolean frequencia) {
        this.frequencia = frequencia;
    }


}


