package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Local generated by hbm2java
 */
@Entity
@Table(name="local"
    ,catalog="sge"
)
public class Local  implements java.io.Serializable {


     private int idLocal;
     private String descricao;
     private Integer capacidade;
     private Set propostas = new HashSet(0);

    public Local() {
    }

	
    public Local(int idLocal) {
        this.idLocal = idLocal;
    }
    public Local(int idLocal, String descricao, Integer capacidade, Set propostas) {
       this.idLocal = idLocal;
       this.descricao = descricao;
       this.capacidade = capacidade;
       this.propostas = propostas;
    }
   
     @Id 

    
    @Column(name="idLocal", unique=true, nullable=false)
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }

    
    @Column(name="descricao", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="capacidade")
    public Integer getCapacidade() {
        return this.capacidade;
    }
    
    public void setCapacidade(Integer capacidade) {
        this.capacidade = capacidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="local")
    public Set getPropostas() {
        return this.propostas;
    }
    
    public void setPropostas(Set propostas) {
        this.propostas = propostas;
    }




}


