package model;
// Generated 09/05/2017 07:49:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proposta generated by hbm2java
 */
@Entity
@Table(name="proposta"
    ,catalog="sge"
)
public class Proposta  implements java.io.Serializable {


     private int idProposta;
     private Evento evento;
     private Gerente gerente;
     private Local local;
     private String proponente;
     private String emailProponente;
     private String tipoAtividade;
     private String tituloAtividade;
     private String finalidadeAtividade;
     private String cargaHoraria;
     private Integer vagasAtividade;
     private String nomeConvidado;
     private String emailConvidado;
     private String formacaoConvidado;
     private String origem;
     private String informacoesComplementares;
     private int diaria;
     private String estado;
     private String publicoAlvo;
     private Integer publicoTodos;
     private Integer publicoInformatica;
     private Integer publicoEdificacoes;
     private Integer publicoEletromecanica;
     private Integer publicoEletrotecnica;
     private Integer publicoMecanica;
     private Integer publicoMetalurgia;
     private Integer publicoEventos;
     private Integer publicoSecretariado;
     private Integer publicoDesignMoveis;
     private Integer publicoEletronica;
     private Integer publicoTransacoesImobiliarias;
     private Integer publicoTransporteFerroviario;
     private Integer publicoSistemasInformacao;
     private Integer publicoEngMecatronica;
     private Integer publicoEngMetalurgica;
     private Integer publicoFisica;
     private Integer segunda;
     private Integer terca;
     private Integer quarta;
     private Integer quinta;
     private Integer sexta;
     private Integer sabado;
     private String dataInicio;
     private String dataFim;

    public Proposta() {
    }

	
    public Proposta(int idProposta, Evento evento, Gerente gerente, Local local, int diaria, String estado, String publicoAlvo, String dataInicio, String dataFim) {
        this.idProposta = idProposta;
        this.evento = evento;
        this.gerente = gerente;
        this.local = local;
        this.diaria = diaria;
        this.estado = estado;
        this.publicoAlvo = publicoAlvo;
        this.dataInicio = dataInicio;
        this.dataFim = dataFim;
    }
    public Proposta(int idProposta, Evento evento, Gerente gerente, Local local, String proponente, String emailProponente, String tipoAtividade, String tituloAtividade, String finalidadeAtividade, String cargaHoraria, Integer vagasAtividade, String nomeConvidado, String emailConvidado, String formacaoConvidado, String origem, String informacoesComplementares, int diaria, String estado, String publicoAlvo, Integer publicoTodos, Integer publicoInformatica, Integer publicoEdificacoes, Integer publicoEletromecanica, Integer publicoEletrotecnica, Integer publicoMecanica, Integer publicoMetalurgia, Integer publicoEventos, Integer publicoSecretariado, Integer publicoDesignMoveis, Integer publicoEletronica, Integer publicoTransacoesImobiliarias, Integer publicoTransporteFerroviario, Integer publicoSistemasInformacao, Integer publicoEngMecatronica, Integer publicoEngMetalurgica, Integer publicoFisica, Integer segunda, Integer terca, Integer quarta, Integer quinta, Integer sexta, Integer sabado, String dataInicio, String dataFim) {
       this.idProposta = idProposta;
       this.evento = evento;
       this.gerente = gerente;
       this.local = local;
       this.proponente = proponente;
       this.emailProponente = emailProponente;
       this.tipoAtividade = tipoAtividade;
       this.tituloAtividade = tituloAtividade;
       this.finalidadeAtividade = finalidadeAtividade;
       this.cargaHoraria = cargaHoraria;
       this.vagasAtividade = vagasAtividade;
       this.nomeConvidado = nomeConvidado;
       this.emailConvidado = emailConvidado;
       this.formacaoConvidado = formacaoConvidado;
       this.origem = origem;
       this.informacoesComplementares = informacoesComplementares;
       this.diaria = diaria;
       this.estado = estado;
       this.publicoAlvo = publicoAlvo;
       this.publicoTodos = publicoTodos;
       this.publicoInformatica = publicoInformatica;
       this.publicoEdificacoes = publicoEdificacoes;
       this.publicoEletromecanica = publicoEletromecanica;
       this.publicoEletrotecnica = publicoEletrotecnica;
       this.publicoMecanica = publicoMecanica;
       this.publicoMetalurgia = publicoMetalurgia;
       this.publicoEventos = publicoEventos;
       this.publicoSecretariado = publicoSecretariado;
       this.publicoDesignMoveis = publicoDesignMoveis;
       this.publicoEletronica = publicoEletronica;
       this.publicoTransacoesImobiliarias = publicoTransacoesImobiliarias;
       this.publicoTransporteFerroviario = publicoTransporteFerroviario;
       this.publicoSistemasInformacao = publicoSistemasInformacao;
       this.publicoEngMecatronica = publicoEngMecatronica;
       this.publicoEngMetalurgica = publicoEngMetalurgica;
       this.publicoFisica = publicoFisica;
       this.segunda = segunda;
       this.terca = terca;
       this.quarta = quarta;
       this.quinta = quinta;
       this.sexta = sexta;
       this.sabado = sabado;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
    }
   
     @Id 

    
    @Column(name="idProposta", unique=true, nullable=false)
    public int getIdProposta() {
        return this.idProposta;
    }
    
    public void setIdProposta(int idProposta) {
        this.idProposta = idProposta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evento_id", nullable=false)
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gerente_codGerente", nullable=false)
    public Gerente getGerente() {
        return this.gerente;
    }
    
    public void setGerente(Gerente gerente) {
        this.gerente = gerente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="local_id", nullable=false)
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }

    
    @Column(name="proponente", length=45)
    public String getProponente() {
        return this.proponente;
    }
    
    public void setProponente(String proponente) {
        this.proponente = proponente;
    }

    
    @Column(name="emailProponente", length=45)
    public String getEmailProponente() {
        return this.emailProponente;
    }
    
    public void setEmailProponente(String emailProponente) {
        this.emailProponente = emailProponente;
    }

    
    @Column(name="tipoAtividade", length=45)
    public String getTipoAtividade() {
        return this.tipoAtividade;
    }
    
    public void setTipoAtividade(String tipoAtividade) {
        this.tipoAtividade = tipoAtividade;
    }

    
    @Column(name="tituloAtividade", length=45)
    public String getTituloAtividade() {
        return this.tituloAtividade;
    }
    
    public void setTituloAtividade(String tituloAtividade) {
        this.tituloAtividade = tituloAtividade;
    }

    
    @Column(name="finalidadeAtividade", length=100)
    public String getFinalidadeAtividade() {
        return this.finalidadeAtividade;
    }
    
    public void setFinalidadeAtividade(String finalidadeAtividade) {
        this.finalidadeAtividade = finalidadeAtividade;
    }

    
    @Column(name="cargaHoraria", length=45)
    public String getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(String cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    
    @Column(name="vagasAtividade")
    public Integer getVagasAtividade() {
        return this.vagasAtividade;
    }
    
    public void setVagasAtividade(Integer vagasAtividade) {
        this.vagasAtividade = vagasAtividade;
    }

    
    @Column(name="nomeConvidado", length=45)
    public String getNomeConvidado() {
        return this.nomeConvidado;
    }
    
    public void setNomeConvidado(String nomeConvidado) {
        this.nomeConvidado = nomeConvidado;
    }

    
    @Column(name="emailConvidado", length=45)
    public String getEmailConvidado() {
        return this.emailConvidado;
    }
    
    public void setEmailConvidado(String emailConvidado) {
        this.emailConvidado = emailConvidado;
    }

    
    @Column(name="formacaoConvidado", length=45)
    public String getFormacaoConvidado() {
        return this.formacaoConvidado;
    }
    
    public void setFormacaoConvidado(String formacaoConvidado) {
        this.formacaoConvidado = formacaoConvidado;
    }

    
    @Column(name="origem", length=45)
    public String getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(String origem) {
        this.origem = origem;
    }

    
    @Column(name="informacoesComplementares", length=100)
    public String getInformacoesComplementares() {
        return this.informacoesComplementares;
    }
    
    public void setInformacoesComplementares(String informacoesComplementares) {
        this.informacoesComplementares = informacoesComplementares;
    }

    
    @Column(name="diaria", nullable=false)
    public int getDiaria() {
        return this.diaria;
    }
    
    public void setDiaria(int diaria) {
        this.diaria = diaria;
    }

    
    @Column(name="estado", nullable=false, length=15)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="publico_alvo", nullable=false, length=20)
    public String getPublicoAlvo() {
        return this.publicoAlvo;
    }
    
    public void setPublicoAlvo(String publicoAlvo) {
        this.publicoAlvo = publicoAlvo;
    }

    
    @Column(name="publico_todos")
    public Integer getPublicoTodos() {
        return this.publicoTodos;
    }
    
    public void setPublicoTodos(Integer publicoTodos) {
        this.publicoTodos = publicoTodos;
    }

    
    @Column(name="publico_informatica")
    public Integer getPublicoInformatica() {
        return this.publicoInformatica;
    }
    
    public void setPublicoInformatica(Integer publicoInformatica) {
        this.publicoInformatica = publicoInformatica;
    }

    
    @Column(name="publico_edificacoes")
    public Integer getPublicoEdificacoes() {
        return this.publicoEdificacoes;
    }
    
    public void setPublicoEdificacoes(Integer publicoEdificacoes) {
        this.publicoEdificacoes = publicoEdificacoes;
    }

    
    @Column(name="publico_eletromecanica")
    public Integer getPublicoEletromecanica() {
        return this.publicoEletromecanica;
    }
    
    public void setPublicoEletromecanica(Integer publicoEletromecanica) {
        this.publicoEletromecanica = publicoEletromecanica;
    }

    
    @Column(name="publico_eletrotecnica")
    public Integer getPublicoEletrotecnica() {
        return this.publicoEletrotecnica;
    }
    
    public void setPublicoEletrotecnica(Integer publicoEletrotecnica) {
        this.publicoEletrotecnica = publicoEletrotecnica;
    }

    
    @Column(name="publico_mecanica")
    public Integer getPublicoMecanica() {
        return this.publicoMecanica;
    }
    
    public void setPublicoMecanica(Integer publicoMecanica) {
        this.publicoMecanica = publicoMecanica;
    }

    
    @Column(name="publico_metalurgia")
    public Integer getPublicoMetalurgia() {
        return this.publicoMetalurgia;
    }
    
    public void setPublicoMetalurgia(Integer publicoMetalurgia) {
        this.publicoMetalurgia = publicoMetalurgia;
    }

    
    @Column(name="publico_eventos")
    public Integer getPublicoEventos() {
        return this.publicoEventos;
    }
    
    public void setPublicoEventos(Integer publicoEventos) {
        this.publicoEventos = publicoEventos;
    }

    
    @Column(name="publico_secretariado")
    public Integer getPublicoSecretariado() {
        return this.publicoSecretariado;
    }
    
    public void setPublicoSecretariado(Integer publicoSecretariado) {
        this.publicoSecretariado = publicoSecretariado;
    }

    
    @Column(name="publico_designMoveis")
    public Integer getPublicoDesignMoveis() {
        return this.publicoDesignMoveis;
    }
    
    public void setPublicoDesignMoveis(Integer publicoDesignMoveis) {
        this.publicoDesignMoveis = publicoDesignMoveis;
    }

    
    @Column(name="publico_eletronica")
    public Integer getPublicoEletronica() {
        return this.publicoEletronica;
    }
    
    public void setPublicoEletronica(Integer publicoEletronica) {
        this.publicoEletronica = publicoEletronica;
    }

    
    @Column(name="publico_transacoesImobiliarias")
    public Integer getPublicoTransacoesImobiliarias() {
        return this.publicoTransacoesImobiliarias;
    }
    
    public void setPublicoTransacoesImobiliarias(Integer publicoTransacoesImobiliarias) {
        this.publicoTransacoesImobiliarias = publicoTransacoesImobiliarias;
    }

    
    @Column(name="publico_transporteFerroviario")
    public Integer getPublicoTransporteFerroviario() {
        return this.publicoTransporteFerroviario;
    }
    
    public void setPublicoTransporteFerroviario(Integer publicoTransporteFerroviario) {
        this.publicoTransporteFerroviario = publicoTransporteFerroviario;
    }

    
    @Column(name="publico_sistemasInformacao")
    public Integer getPublicoSistemasInformacao() {
        return this.publicoSistemasInformacao;
    }
    
    public void setPublicoSistemasInformacao(Integer publicoSistemasInformacao) {
        this.publicoSistemasInformacao = publicoSistemasInformacao;
    }

    
    @Column(name="publico_engMecatronica")
    public Integer getPublicoEngMecatronica() {
        return this.publicoEngMecatronica;
    }
    
    public void setPublicoEngMecatronica(Integer publicoEngMecatronica) {
        this.publicoEngMecatronica = publicoEngMecatronica;
    }

    
    @Column(name="publico_engMetalurgica")
    public Integer getPublicoEngMetalurgica() {
        return this.publicoEngMetalurgica;
    }
    
    public void setPublicoEngMetalurgica(Integer publicoEngMetalurgica) {
        this.publicoEngMetalurgica = publicoEngMetalurgica;
    }

    
    @Column(name="publico_fisica")
    public Integer getPublicoFisica() {
        return this.publicoFisica;
    }
    
    public void setPublicoFisica(Integer publicoFisica) {
        this.publicoFisica = publicoFisica;
    }

    
    @Column(name="segunda")
    public Integer getSegunda() {
        return this.segunda;
    }
    
    public void setSegunda(Integer segunda) {
        this.segunda = segunda;
    }

    
    @Column(name="terca")
    public Integer getTerca() {
        return this.terca;
    }
    
    public void setTerca(Integer terca) {
        this.terca = terca;
    }

    
    @Column(name="quarta")
    public Integer getQuarta() {
        return this.quarta;
    }
    
    public void setQuarta(Integer quarta) {
        this.quarta = quarta;
    }

    
    @Column(name="quinta")
    public Integer getQuinta() {
        return this.quinta;
    }
    
    public void setQuinta(Integer quinta) {
        this.quinta = quinta;
    }

    
    @Column(name="sexta")
    public Integer getSexta() {
        return this.sexta;
    }
    
    public void setSexta(Integer sexta) {
        this.sexta = sexta;
    }

    
    @Column(name="sabado")
    public Integer getSabado() {
        return this.sabado;
    }
    
    public void setSabado(Integer sabado) {
        this.sabado = sabado;
    }

    
    @Column(name="dataInicio", nullable=false, length=11)
    public String getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(String dataInicio) {
        this.dataInicio = dataInicio;
    }

    
    @Column(name="dataFim", nullable=false, length=11)
    public String getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(String dataFim) {
        this.dataFim = dataFim;
    }


}


